## User params ## 

DATA_DIR: data/

FORMAT: 2019
WEIGHT1: resources/weights/FL.t.old.hd5
WEIGHT2: None

I: [1,2,3,4]

## Advanced params ##
# (Please don't change unless you're developer)

# blob detection
test_mode: False
equalization: True  # hard code: yes in blob detection, no in CNN
block_height: 2000
block_width: 2400  # if < 0, skip block equalization
scaling_factor: 4  # 1, 2, 4 (08/23/2021 for blob_detection)
max_sigma: 6 # 20-50
min_sigma: 3  # 2-8
num_sigma: 20  # smaller->faster, less accurate, 5-20
threshold: 0.02
blob_detection_visualization: True
blob_extention_ratio: 1.0 # soft extend blob radius manually (1.4)
blob_extention_radius: 0 # pixcels to extend (2)
crop_width: 80  # padding width, which is cropped img width/2 (50)
overlap: .8


# CNN 
classification_equalization: True  # wether use equ for model training/classification
clas_scaling_factor: 2  # input scale down for model training
aug_sample_size: 2000
training_ratio: 0.9  # proportion of data to be in training set
r_ext_ratio: 1.0  # larger (1.4) for better view under augmentation
r_ext_pixels: 0
numClasses: 2  # if 2, all other than 1 will be zero
batch_size: 64  # default 64
patience: 3  # default 50
learning_rate: 0.0001  # default 0.0001 (Adam)
verbose: 2  # {0, 1, 2}

# Notes

## 2018 params recommendation
# if scaling_factor == 1:
#     max_sigma=50 
#     min_sigma=5
#     num_sigma=15
#     threshold=0.1
# elif scaling_factor == 2:
#     max_sigma=40
#     min_sigma=2
#     num_sigma=10
#     threshold=0.1
# elif scaling_factor == 4 and FL:
  # max_sigma: 5 # 20-50 
  # min_sigma: 2  # 2-8
  # num_sigma: 20  # smaller->faster, less accurate, 5-20
  # threshold: 0.02
# else:
#     raise Exception("scaling factor not implemented")