configfile: "config.yaml"
import os

SAMPLES=config["SAMPLES"]
FORMAT=config["FORMAT"]
WEIGHT1=config["WEIGHT1"]
WEIGHT2=config["WEIGHT2"]
WKDIR=os.getcwd()

shell.prefix("""
            # placeholder
            """)

rule targets:
    input:
        img=expand("res/img/jpg/{s}.jpg", s=SAMPLES),  # czi2img
        blobs=expand("res/blobs/{s}.npy.gz", s=SAMPLES),  # blob_detection
        view0=expand("res/blobs/{s}.html", s=SAMPLES),  # rand samples of detected blobs
#        count1="count/COUNT.txt",  # count from weight1
#        count2="count/COUNT.step1_test.txt", # count from weight1-pos -> weight2-pos
#        view1=expand("filter1/view/{s}.html", s=SAMPLES), # view weight1-pos
#        view2=expand("filter2/view/{s}.html", s=SAMPLES) # view weight1-weight2-pos

rule czi2img:
    input:
        "data/{s}.czi"
    output:
        "res/img/jpg/{s}.jpg",
        "res/img/equ/{s}.equ.jpg",
    priority: 
        0
    threads:
        1
    log:
        "res/img/log/{s}.log"
    benchmark:
        "res/img/log/{s}.tsv"
    params:
        mem='40000'
    shell:
        """
        python scripts/czi2img.py -i {input} -f {FORMAT} -odir res/img &> {log}
        """
    
rule blob_detection:
    input:
        "data/{s}.czi"
    output:
        "res/blobs/{s}.npy.gz"
    priority:
        100
    threads:
        1
    log:
        "res/blobs/{s}.log"
    benchmark:
        "res/blobs/{s}.tsv"
    params:
        mem="45000"
    shell:
        """
        python scripts/blob_detection.py -i {input} -f {FORMAT} -odir res/blobs/ &> {log}
        """

rule view0:
    input:
        "res/blobs/{s}.npy.gz"
    output:
        nb="res/blobs/{s}.ipynb",
        html="res/blobs/{s}.html"
    log:
        "res/blobs/{s}.html.log"
    benchmark:
        "res/blobs/{s}.html.tsv"
    threads:
        1
    params:
        mem="8000"
    shell:
        """
        fname={input} dir={WKDIR} runipy scripts/viewing_blobs.ipynb {output.nb} &> {log}
        jupyter nbconvert --to html {output.nb} &>> {log}
        """

rule filter1:
    input:
        "res/blobs/{s}.npy.gz"
    output:
        yes="res/filter1/{s}.yes.npy.gz",
        all="res/filter1/{s}.pred.npy.gz",
        log="res/filter1/{s}.log"
    benchmark:
        "res/filter1/{s}.tsv"
    threads:
        1
    params:
        mem="8000"
    shell:
        """
        python scripts/classification.py  -db {input} -o res/filter1 -l 1 -w {WEIGHT1} &> {output.log}
        """


rule filter2:
    input:
        "res/filter1/{s}.yes.npy.gz"
    output:
        yes="res/filter2/{s}.yes.yes.npy.gz",
        all="res/filter2/{s}.yes.pred.npy.gz",
        log="res/filter2/{s}.log"
    benchmark:
        "res/filter2/{s}.tsv"
    threads:
        1
    params:
        mem="8000"
    shell:
        """
        python scripts/classification.py  -db {input} -o res/filter2 -l 1 -w {WEIGHT2} &> {output.log}
        """


rule count1:
    input:
        expand("res/filter1/{s}.log", s=SAMPLES)
    output:
        "res/filter1/COUNT1.txt"
    threads:
        1
    params:
        mem="1000"
    shell:
        """
        grep 'Predictions' {input} > {output}
        """

rule count2:
    input:
        expand("res/filter2/{s}.log", s=SAMPLES)
    output:
        "res/filter2/COUNT2.txt"
    threads:
        1
    params:
        mem="1000"
    shell:
        """
        grep 'Predictions' {input} > {output}
        """


rule view1:
    input:
        "res/filter1/{s}.pred.npy.gz"
    output:
        nb="res/filter1/{s}.ipynb",
        html="res/filter1/{s}.html"
    log:
        "res/filter1/{s}.html.log"
    benchmark:
        "res/filter1/{s}.html.tsv"
    threads:
        1
    params:
        mem="8000"
    shell:
        """
        fname={input} dir={WKDIR} runipy scripts/viewing_blobs.ipynb {output.nb} &> {log}
        jupyter nbconvert --to html {output.nb} &>> {log}
        """


rule view2:
    input:
        "res/filter2/{s}.yes.pred.npy.gz"
    output:
        nb="res/filter2/{s}.ipynb",
        html="res/filter2/{s}.html"
    log:
        "res/filter2/{s}.html.log"
    benchmark:
        "res/filter2/{s}.html.tsv"
    threads:
        1
    params:
        mem="8000"
    shell:
        """
        fname={input} dir={WKDIR} runipy scripts/viewing_blobs.ipynb {output.nb} &> {log}
        jupyter nbconvert --to html {output.nb} &>> {log}
        """


